Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
  end
  config.disksize.size = '100GB'
  config.vm.synced_folder "shared/", "/home/vagrant/shared"
  config.vm.synced_folder "/Users/thomas.greenwood/.notable", "/home/vagrant/.notable"

  # File transfers ------------------------------------------------------------

  # Github ssh (so don't need to add a newe key to github every time)
  config.vm.provision "shell", inline: "mkdir -p ~/.ssh"
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "~/.ssh/id_rsa_personal", destination: "~/.ssh/id_rsa_personal"
  config.vm.provision "file", source: "~/.ssh/id_rsa_personal.pub", destination: "~/.ssh/id_rsa_personal.pub"
  # ===========================================================================

  # Updates -------------------------------------------------------------------
  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision "shell", inline: "dpkg --configure -a"
  config.vm.provision "shell", inline: "apt-get upgrade -y"
  # ===========================================================================

  # Utils install -------------------------------------------------------------
  config.vm.provision "shell", inline: "apt-get install -y linux-headers-$(uname -r)"
  config.vm.provision "shell", inline: "apt-get install -y build-essential"
  config.vm.provision "shell", inline: "apt-get install -y dkms"
  config.vm.provision "shell", inline: "apt-get install -y virtualbox-guest-dkms"
  config.vm.provision "shell", inline: "apt-get install -y virtualbox-guest-utils"
  config.vm.provision "shell", inline: "apt-get install -y virtualbox-guest-x11"
  config.vm.provision "shell", inline: "apt-get install -y tree"
  config.vm.provision "shell", inline: "apt-get install -y ubuntu-desktop"
  config.vm.provision "shell", inline: "git config --global user.name 'Tom Greenwood'"
  config.vm.provision "shell", inline: "git config --global user.email 'thomas.greenwood@kainos.com'"
  config.vm.provision "shell", inline: "git clone git@github.com-personal:TomGreenwood10/dev.git /home/vagrant/"
  # ===========================================================================

  config.vm.provision "shell", inline: "sudo shutdown"
end
